### ISSUE TITLE
Creating a ticket redirects? PHP

### ISSUE THREAD

**Issue by EvanHerman** [freshdesk/fresh-samples#16]
I'm using the [sample PHP](https://github.com/freshdesk/fresh-samples/blob/master/php_samples/create_ticket.php) code to try and create a ticket via cURL. It seems that the response I'm getting back is "You are being redirected."

The ticket isn't being created either. Is there some reason this would be happening that I'm overlooking? 

I've copied the [PHP sample](https://github.com/freshdesk/fresh-samples/blob/master/php_samples/create_ticket.php) code verbatim, but swapped out the fd_domain, token and cc_emails (inside the data arraay).

Thanks,
Evan

**Comment by EvanHerman** [comment]
Sorry, it seems that the endpoint (in my case) should begin https:// instead of http://.

Thanks

**Comment by adarshvsukumaran** [comment]
Hi,
I have changed to https but still the ticket is not created. Do we need to change anything in the admin panel?
Thanks

**Comment by rseetharamaguptha** [comment]
Which file are u trying to execute ?

**Comment by adarshvsukumaran** [comment]
Hii..Thanks for the replay.

I got a sample php code from github.
https://github.com/freshdesk/fresh-samples/blob/v1/php_samples/create_ticket_with_custom_field.php
I added my api key, and login details. Then tries to execute from my localhost. No response from curl.

**Comment by rseetharamaguptha** [comment]
Hi,

If you are trying it first time, I suggest you to use the V2 API instead of V1. We'll be deprecating the V1 API soon. Please tryout the samples in V2 from this [link](https://github.com/freshdesk/fresh-samples/tree/master/PHP)

thanks.

**Comment by adarshvsukumaran** [comment]
Hi,
I have tried V2, but i am getting status code : 0. 

'Error, HTTP Status Code : 0 Headers are Response are '

i have tried solve it by adding the below code.
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 20);
Still it is not working.

**Comment by rseetharamaguptha** [comment]
Update the values for the following variables in the sample file,

$api_key = "API_KEY"; 
$password = "x";
$yourdomain = "YOUR_DOMAIN";

**$api_key = API_KEY;**  is unique key which can be obtained from the user profile page of the 
Freshdesk APP
**$password = "x";** leave it as it is

**$yourdomain = "YOUR_DOMAIN"; ** your domain name, **sample** is the domain name in **sample.freshdesk.com**

Dont modify other lines in the code. You start with this [file](https://github.com/freshdesk/fresh-samples/blob/master/PHP/create_ticket.php). Documentation can be accessed from this [link](developers.freshdesk.com/api)
