### ISSUE TITLE
How can I post more than one attachments?

### ISSUE THREAD

**Issue by vslovik** [freshdesk/fresh-samples#48]
https://github.com/freshdesk/fresh-samples/blob/8de3cee918be7e3fc2f89921f5c4b9a4dbbfc7bd/PHP/create_ticket_with_attachment.php#L13

**Comment by NettoPassaro** [comment]
Could you solve this question?

I'm trying add curl_file_create() files into a array, but getting:
{"description":"Validation failed","errors":[{"field":"attachments","message":"It should contain elements of type valid file format only","code":"datatype_mismatch"}]}

**Comment by NettoPassaro** [comment]
Now i get it with other example...

[here](https://github.com/freshdesk/fresh-samples/blob/master/PHP/create_ticket_with_multiple_attachments.php)

**Comment by hrishikesh-p** [comment]
https://github.com/freshdesk/fresh-samples/blob/master/PHP/create_ticket_with_multiple_attachments.php
