### ISSUE TITLE
Please document freshplug api helper methods 

### ISSUE THREAD

**Issue by blak3r** [freshdesk/fresh-samples#5]
Would be nice to have a little more documentation on say the freshdesk proxy

`var proxy = new Freshdesk.Widget(opts);`

And what you can and cannot do with the `CustomWidget.include_js()` like will it handle placeholders inside my widget?  Can i include html/style in it as well? So, that i don't need to keep pasting it in to the Freshplug ui.

**Comment by prasadmunna** [comment]
hi.. i am using text summer text editor for posting data on fresh desk ticket, but after i inserted image it was post as html content like this
<p>test<img src="http://localhost/automation/public/source/56937cb8e76f1_attachment.png" style="width: 210px;"></p>

Can you please help me , i am using PHP api for reply fresh desk ticket.

Thanks

**Comment by prasadmunna** [comment]
hi.. i am using text summer text editor for posting data on fresh desk ticket, but after i inserted image it was post as html content like this
<pre><p>test<img src="http://localhost/automation/public/source/56937cb8e76f1_attachment.png" style="width: 210px;"></p></pre>

Can you please help me , i am using PHP api for reply fresh desk ticket.

Thanks
