### ISSUE TITLE
new feature: real time interface with Freshdesk

### ISSUE THREAD

**Issue by ispirante** [freshdesk/fresh-samples#8]
I'm trying to build a real time interface with Freshdesk and I'd like an API that would let me fetch tickets information querying for the tickets updated after a certain instant in time.
i.e., I'd like to load all the tickets updated after the 1st of January 2015 with an API call such as
curl https://{subdomain}.freshdesk.com/api/....?start_time=1442000000 -v -u {email_address}:{password}.

What I'd expect is an API that returns a set of tickets updated after that date and a pointer to next page of tickets (if any). This is a pretty common pattern and it exist in most of the other SaaS CRM tools.
Without it I don't see any way to build a real time interface with Freshdesk.
If this feature in your roadmap and if yes when is it planned to be released ?

**Comment by subwiz** [comment]
We still don't have support for this API. We are evaluating the possibility of building this. Will keep you posted on the progress.

**Comment by ispirante** [comment]
I haven't heard anything yet. any news or plan about this feature?
Thanks

**Comment by sudhircirra** [comment]
We still don't have support for this API. I would suggest you to log a ticket in Freshdesk's support system or by sending an email to support@freshdesk.com. This way, you would be automatically informed of any updates related to your request.

**Comment by rohitfreshdesk** [comment]
We have included this API as part of the new generation v2.0 APIs - http://developer.freshdesk.com/api/#list_all_tickets. The updated_since filter will enable you to get only the tickets that you need. It's still in beta, but you can try it out and see if it meets your needs.

**Comment by sudhircirra** [comment]
API V2 is now GA. List all tickets API with `updated_since` filter is now available. For more info, please see http://developer.freshdesk.com/api/#list_all_tickets.
